In [153]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split

In [154]:
# load preprocessed train dataset
df_train = pd.read_csv('titanic_train_preprocessed2.csv')

# create matrix of the features (X) and target (y)
X = df_train.drop('Survived',axis=1) # values used for prediction
y = df_train['Survived'] # values to be predicted

# split data from "titanic_train_preprocessed.csv" to training data (75%) and testing data (25%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
X_train

Age  SibSp  Parch      Fare  female   male  Master   Miss     Mr  \
298  28.00      0      0   30.5000   False   True   False  False   True   
884  25.00      0      0    7.0500   False   True   False  False   True   
247  24.00      0      2   14.5000    True  False   False  False  False   
478  22.00      0      0    7.5208   False   True   False  False   True   
305   0.92      1      2  151.5500   False   True    True  False  False   
..     ...    ...    ...       ...     ...    ...     ...    ...    ...   
106  21.00      0      0    7.6500    True  False   False   True  False   
270  28.00      0      0   31.0000   False   True   False  False   True   
860  41.00      2      0   14.1083   False   True   False  False   True   
435  14.00      1      2  120.0000    True  False   False   True  False   
102  21.00      0      1   77.2875   False   True   False  False   True   

       Mrs      1      2      3  
298  False   True  False  False  
884  False  False  False   True  
247   True  False   True  False  
478  False  False  False   True  
305  False   True  False  False  
..     ...    ...    ...    ...  
106  False  False  False   True  
270  False   True  False  False  
860  False  False  False   True  
435  False   True  False  False  
102  False   True  False  False  

[668 rows x 13 columns]

In [156]:
X_train = np.asarray(X_train).astype(np.float32) # cause of error: Failed to convert a NumPy array to a Tensor
y_train = np.asarray(y_train).astype(np.float32) 
X_test = np.asarray(X_test).astype(np.float32) 
y_test = np.asarray(y_test).astype(np.float32) 
X = np.asarray(X).astype(np.float32)
y = np.asarray(y).astype(np.float32)

model = Sequential()
model.add(Dense(512, input_shape=(13,), activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


converted_data = pd.DataFrame(X_train)
converted_data.to_csv('x_train_float32.csv', index=False)

In [150]:
model.fit(X_train, y_train, epochs=100, batch_size=10)

ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).

In [132]:
# Make predictions on the test set
y_pred = model.predict(X_test)
y_pred = np.asarray(y_pred).astype(np.int64)
y_pred

7/7 [==============================] - 0s 2ms/step


array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [133]:
# Calculate the accuracy of the model
from sklearn.metrics import accuracy_score 
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.5964125560538116


In [134]:
# once happy with the model accuracy, fit it on all data
model.fit(X, y, epochs=100, batch_size=10)

Epoch 1/100
90/90 [==============================] - 0s 2ms/step - loss: 0.5562 - accuracy: 0.8092
Epoch 2/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4358 - accuracy: 0.8092
Epoch 3/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4149 - accuracy: 0.8137
Epoch 4/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4242 - accuracy: 0.8283
Epoch 5/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4192 - accuracy: 0.8171
Epoch 6/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8193
Epoch 7/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4109 - accuracy: 0.8215
Epoch 8/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4034 - accuracy: 0.8182
Epoch 9/100
90/90 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8159
Epoch 10/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3938 - accuracy: 0.8249
Epoch 11/

90/90 [==============================] - 0s 2ms/step - loss: 0.3423 - accuracy: 0.8474
Epoch 84/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3501 - accuracy: 0.8462
Epoch 85/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3539 - accuracy: 0.8474
Epoch 86/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3290 - accuracy: 0.8519
Epoch 87/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3562 - accuracy: 0.8507
Epoch 88/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3544 - accuracy: 0.8440
Epoch 89/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3604 - accuracy: 0.8384
Epoch 90/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3322 - accuracy: 0.8552
Epoch 91/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3510 - accuracy: 0.8440
Epoch 92/100
90/90 [==============================] - 0s 2ms/step - loss: 0.3837 - accuracy: 0.8339
Epoch 93/100


In [135]:
X_pred = pd.read_csv('titanic_test_preprocessed.csv')
X_pred.replace([np.inf, -np.inf], np.nan, inplace=True) # becaouse of error NaN/inf
X_pred.fillna(999, inplace=True) # becaouse of error NaN/inf
X_pred.head()

PassengerId   Age  SibSp  Parch     Fare      2      3   male      Q  \
0          892  34.5      0      0   7.8292  False   True   True   True   
1          893  47.0      1      0   7.0000  False   True  False  False   
2          894  62.0      0      0   9.6875   True  False   True   True   
3          895  27.0      0      0   8.6625  False   True   True  False   
4          896  22.0      1      1  12.2875  False   True  False  False   

       S   Miss     Mr    Mrs  
0  False  False   True  False  
1   True  False  False   True  
2  False  False   True  False  
3   True  False   True  False  
4   True  False  False   True

In [136]:
X_pred_convert = np.nan_to_num(X_pred) # conversion, otherwise y_pred throws an error
X_pred_convert = np.asarray(X_pred_convert).astype(np.float32)

In [137]:
y_pred_all = model.predict(X_pred_convert)
y_pred_all

14/14 [==============================] - 0s 2ms/step


array([[0.03761048],
       [0.25310695],
       [0.06612486],
       [0.03300935],
       [0.4214758 ],
       [0.08718682],
       [0.5156815 ],
       [0.09812428],
       [0.88574284],
       [0.03032201],
       [0.03138824],
       [0.13347219],
       [0.99945766],
       [0.08748962],
       [0.9960982 ],
       [0.9943686 ],
       [0.1311424 ],
       [0.0392967 ],
       [0.2031857 ],
       [0.5606372 ],
       [0.57591796],
       [0.70889336],
       [0.9904896 ],
       [0.6679197 ],
       [0.9483659 ],
       [0.02521634],
       [0.9981485 ],
       [0.03766945],
       [0.19168214],
       [0.03033537],
       [0.08796033],
       [0.09804881],
       [0.31142125],
       [0.4510208 ],
       [0.4037061 ],
       [0.04722293],
       [0.3676448 ],
       [0.5026451 ],
       [0.03215994],
       [0.33789167],
       [0.03285532],
       [0.18832904],
       [0.02617314],
       [0.9526111 ],
       [0.9947277 ],
       [0.02947315],
       [0.22190702],
       [0.036

In [138]:
y_pred_all = np.where(y_pred <= 0.5, 0, 1) # convert float numbers between 0 and 1 to only 0 or 1
y_pred_all

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [144]:
# convert numpy ndarray back to dataframe
#predicted_data = pd.DataFrame(y_pred_all)

# append the predicted data to final file
df_test = pd.read_csv('titanic_test_preprocessed.csv')
df_test = pd.concat([df_test,predicted_data],axis=1) # append predicted y
df_test = df_test.rename(columns = {0:'Survived'}) # rename added column
df_test = df_test[['PassengerId', 'Survived']] # leave only requested columns for submit
df_test # check if correct

PassengerId  Survived
0            892       0.0
1            893       0.0
2            894       0.0
3            895       0.0
4            896       0.0
..           ...       ...
413         1305       NaN
414         1306       NaN
415         1307       NaN
416         1308       NaN
417         1309       NaN

[418 rows x 2 columns]

In [19]:
# save result
df_test.to_csv('submission.csv', index=False)